package by.epam.webpoject.ezmusic.command;

/**
 * Created by Антон on 16.07.2016.
 */
public enum CommandName {
    LOGIN,
    LOGOUT,
    REGISTER,
    CHECK_LOGIN_AVAILABILITY,
    CHANGE_LOCALE,
    GO_HOME,
    DELETE_USER,
    UPDATE_USER,
    FIND_USER,
    CREATE_USER,
    CREATE_SONG,
    FIND_SONG_FOR_UPDATE,
    FIND_SONG_FOR_CREATE,
    FIND_ALL_SONGS,
    DELETE_SONG,
    UPDATE_SONG,
    CREATE_ALBUM,
    UPDATE_ALBUM,
    DELETE_ALBUM,
    FIND_ALL_ALBUMS,
    FIND_ALBUM_FOR_UPDATE,
    FIND_ALBUM_FOR_CREATE,
    FIND_AUTHOR_ALBUMS_JSON,
    FIND_AUTHOR_SONGS_JSON,
    FIND_ALL_AUTHORS,
    FIND_AUTHOR_FOR_CREATE,
}
